
import { GoogleGenAI, Type, Schema } from "@google/genai";
import { SYSTEM_INSTRUCTION, DEFAULT_MODEL } from "../constants";
import { GeneratedContent } from "../types";
import { CONTACT_TEMPLATE, FOOTER_TEMPLATE } from "../templates";

// ─────────────────────────────────────────────────────────────────────────────
// API KEY RESOLUTION — No manual file edits needed
// 
// Priority order:
//   1. GEMINI_API_KEY env variable (set in Render Dashboard → baked in at build)
//   2. API_KEY env variable (legacy support)
//   3. Key saved in browser localStorage (entered via UI key-setup screen)
//
// On Render: Just set GEMINI_API_KEY in the dashboard. That's it. ✓
// Locally:   Set GEMINI_API_KEY in .env.local. That's it. ✓
// ─────────────────────────────────────────────────────────────────────────────

const STORAGE_KEY = 'visinaro_gemini_key';

export const getApiKey = (): string => {
  // 1. Env var (baked in at Render build time)
  const envKey = process.env.GEMINI_API_KEY || process.env.API_KEY || '';
  if (envKey && envKey !== 'PLACEHOLDER_API_KEY' && envKey.length > 10) {
    return envKey;
  }
  // 2. Runtime key saved by user in browser
  try {
    return localStorage.getItem(STORAGE_KEY) || '';
  } catch {
    return '';
  }
};

export const saveApiKey = (key: string): void => {
  try {
    localStorage.setItem(STORAGE_KEY, key.trim());
  } catch { /* ignore */ }
};

export const clearApiKey = (): void => {
  try {
    localStorage.removeItem(STORAGE_KEY);
  } catch { /* ignore */ }
};

export const hasApiKey = (): boolean => {
  return getApiKey().length > 10;
};

// ─────────────────────────────────────────────────────────────────────────────

const getClient = () => {
  const apiKey = getApiKey();
  if (!apiKey) {
    throw new Error("API_KEY_MISSING");
  }
  return new GoogleGenAI({ apiKey });
};

const responseSchema: Schema = {
  type: Type.OBJECT,
  properties: {
    html: { type: Type.STRING, description: "Complete HTML structure with Tailwind classes." },
    css: { type: Type.STRING, description: "Empty string unless custom keyframe animations needed." },
    javascript: { type: Type.STRING, description: "Minimal JavaScript for interactions." },
  },
  required: ["html", "css", "javascript"],
};

const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * Generates a website with streaming for reduced perceived latency.
 */
export const generateWebsite = async (
  prompt: string,
  modelId: string,
  onProgress?: (partial: string) => void
): Promise<GeneratedContent> => {
  const ai = getClient();
  const MAX_RETRIES = 3;
  let lastError: any = null;

  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    try {
      if (onProgress) {
        // Streaming path for perceived speed
        const stream = await ai.models.generateContentStream({
          model: modelId,
          config: {
            systemInstruction: SYSTEM_INSTRUCTION,
            temperature: 0.3,
            responseMimeType: "application/json",
            responseSchema,
            maxOutputTokens: 4096,
          },
          contents: prompt,
        });

        let fullText = '';
        for await (const chunk of stream) {
          fullText += (chunk.text || '');
          onProgress(fullText);
        }

        const content = JSON.parse(fullText) as GeneratedContent;
        return injectTemplates(content);
      }

      // Non-streaming fallback
      const response = await ai.models.generateContent({
        model: modelId,
        config: {
          systemInstruction: SYSTEM_INSTRUCTION,
          temperature: 0.3,
          responseMimeType: "application/json",
          responseSchema,
          maxOutputTokens: 4096,
        },
        contents: prompt,
      });

      const text = response.text;
      if (!text) throw new Error("No content generated by AI.");

      const content = JSON.parse(text) as GeneratedContent;
      return injectTemplates(content);

    } catch (error: any) {
      lastError = error;
      const msg = (error.message || error.toString()).toLowerCase();
      console.warn(`Generation Attempt ${attempt + 1} failed:`, msg);

      if (
        msg.includes('400') || msg.includes('401') || msg.includes('403') ||
        msg.includes('404') || msg.includes('key') || msg.includes('invalid argument') ||
        msg === 'api_key_missing'
      ) {
        break;
      }

      if (attempt < MAX_RETRIES - 1) {
        await wait(800 * Math.pow(2, attempt));
        continue;
      }
    }
  }

  const msg = (lastError?.message || String(lastError)).toLowerCase();

  if (msg === 'api_key_missing' || msg.includes('api_key_missing')) {
    throw new Error("API_KEY_MISSING");
  }
  if (msg.includes('429') || msg.includes('quota') || msg.includes('resource exhausted')) {
    throw new Error("High traffic: API rate limit hit. Please wait 30 seconds and try again.");
  }
  if (msg.includes('401') || msg.includes('403') || msg.includes('key')) {
    throw new Error("API_KEY_INVALID");
  }
  if (msg.includes('503') || msg.includes('overloaded') || msg.includes('internal')) {
    throw new Error("AI service is temporarily busy. Please try again.");
  }
  if (msg.includes('candidate') || msg.includes('safety') || msg.includes('blocked')) {
    throw new Error("Request blocked by safety filters. Please try a different prompt.");
  }

  throw new Error(lastError?.message || "Failed to generate website. Please try again.");
};

/** Injects contact + footer templates */
function injectTemplates(content: GeneratedContent): GeneratedContent {
  if (content.html) {
    content.html = content.html
      .replace(/<!--__TEMPLATE_CONTACT__-->/g, CONTACT_TEMPLATE)
      .replace(/<!--__TEMPLATE_FOOTER__-->/g, FOOTER_TEMPLATE);
  }
  return content;
}

/**
 * SEO Agent: Analyzes generated HTML and returns SEO improvements.
 */
export const optimizeSEO = async (
  generatedHtml: string,
  userPrompt: string
): Promise<{ improvedHtml: string; seoReport: string }> => {
  try {
    const ai = getClient();
    const response = await ai.models.generateContent({
      model: DEFAULT_MODEL,
      config: {
        systemInstruction: `You are an elite SEO specialist. Analyze the HTML and:
1. Add/improve meta tags (title, description, og:tags, twitter:card, canonical)
2. Add JSON-LD structured data
3. Fix semantic HTML (proper h1→h6 hierarchy, aria-labels, alt texts)
4. Add rel="noopener noreferrer" to external links
Return ONLY valid JSON: { "improvedHtml": "<full improved html>", "seoReport": "bullet list of changes" }`,
        temperature: 0.1,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            improvedHtml: { type: Type.STRING },
            seoReport: { type: Type.STRING },
          },
          required: ["improvedHtml", "seoReport"],
        },
      },
      contents: `Website Intent: ${userPrompt}\n\nHTML:\n${generatedHtml.slice(0, 8000)}`,
    });

    const result = JSON.parse(response.text || '{}');
    return {
      improvedHtml: result.improvedHtml || generatedHtml,
      seoReport: result.seoReport || "No changes made.",
    };
  } catch (error) {
    console.error("SEO Optimization Error:", error);
    return { improvedHtml: generatedHtml, seoReport: "SEO optimization unavailable." };
  }
};

/**
 * Enhances a short prompt into a detailed professional one.
 */
export const enhancePrompt = async (simpleIdea: string): Promise<string> => {
  try {
    const ai = getClient();
    const response = await ai.models.generateContent({
      model: DEFAULT_MODEL,
      config: {
        systemInstruction: `You are an expert web consultant. Expand the user's short idea into a detailed, professional website prompt in 3-4 sentences. Output ONLY the prompt text.`,
        temperature: 0.7,
        maxOutputTokens: 256,
      },
      contents: `Expand: ${simpleIdea}`,
    });
    return response.text || simpleIdea;
  } catch (error) {
    return simpleIdea;
  }
};
