
import { GoogleGenAI, Type, Schema } from "@google/genai";
import { SYSTEM_INSTRUCTION, DEFAULT_MODEL, AVAILABLE_MODELS } from "../constants";
import { GeneratedContent } from "../types";
import { CONTACT_TEMPLATE, FOOTER_TEMPLATE } from "../templates";

// ─────────────────────────────────────────────────────────────────────────────
// API KEY RESOLUTION
// Priority: 1. Render env var (baked at build)  2. localStorage (UI entry)
// ─────────────────────────────────────────────────────────────────────────────

const STORAGE_KEY = 'visinaro_gemini_key';

export const getApiKey = (): string => {
  const envKey = process.env.GEMINI_API_KEY || process.env.API_KEY || '';
  if (envKey && envKey !== 'PLACEHOLDER_API_KEY' && envKey.length > 10) return envKey;
  try { return localStorage.getItem(STORAGE_KEY) || ''; } catch { return ''; }
};

export const saveApiKey = (key: string): void => {
  try { localStorage.setItem(STORAGE_KEY, key.trim()); } catch { /* ignore */ }
};

export const clearApiKey = (): void => {
  try { localStorage.removeItem(STORAGE_KEY); } catch { /* ignore */ }
};

export const hasApiKey = (): boolean => getApiKey().length > 10;

// ─────────────────────────────────────────────────────────────────────────────
// RATE LIMIT TRACKING
// Tracks which models have hit quota so we can auto-skip them
// ─────────────────────────────────────────────────────────────────────────────

interface QuotaRecord { until: number; }
const quotaHits: Record<string, QuotaRecord> = {};

const markQuotaHit = (modelId: string) => {
  // Block this model for 60 seconds after a 429
  quotaHits[modelId] = { until: Date.now() + 60_000 };
};

const isQuotaBlocked = (modelId: string): boolean => {
  const rec = quotaHits[modelId];
  if (!rec) return false;
  if (Date.now() > rec.until) { delete quotaHits[modelId]; return false; }
  return true;
};

export const getQuotaWaitSeconds = (modelId: string): number => {
  const rec = quotaHits[modelId];
  if (!rec) return 0;
  return Math.max(0, Math.ceil((rec.until - Date.now()) / 1000));
};

// ─────────────────────────────────────────────────────────────────────────────

const getClient = () => {
  const apiKey = getApiKey();
  if (!apiKey) throw new Error("API_KEY_MISSING");
  return new GoogleGenAI({ apiKey });
};

const responseSchema: Schema = {
  type: Type.OBJECT,
  properties: {
    html: { type: Type.STRING, description: "Complete HTML structure with Tailwind classes." },
    css: { type: Type.STRING, description: "Empty string unless custom keyframe animations needed." },
    javascript: { type: Type.STRING, description: "Minimal JavaScript for mobile menu only." },
  },
  required: ["html", "css", "javascript"],
};

const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

const isQuotaError = (msg: string) =>
  msg.includes('429') || msg.includes('quota') || msg.includes('resource exhausted') ||
  msg.includes('rate limit') || msg.includes('exceeded');

const isNotFoundError = (msg: string) =>
  msg.includes('404') || msg.includes('not found') || msg.includes('not_found');

const isAuthError = (msg: string) =>
  msg.includes('401') || msg.includes('403') ||
  (msg.includes('key') && !msg.includes('not found'));

const isFatalError = (msg: string) =>
  msg.includes('400') || isAuthError(msg) || msg === 'api_key_missing';

// ─────────────────────────────────────────────────────────────────────────────
// CORE GENERATION — with auto-fallback across models on quota errors
// ─────────────────────────────────────────────────────────────────────────────

const tryGenerateWithModel = async (
  ai: GoogleGenAI,
  modelId: string,
  prompt: string,
  onProgress?: (partial: string) => void
): Promise<GeneratedContent> => {
  const config = {
    systemInstruction: SYSTEM_INSTRUCTION,
    temperature: 0.3,
    responseMimeType: "application/json" as const,
    responseSchema,
    maxOutputTokens: 4096,
  };

  if (onProgress) {
    const stream = await ai.models.generateContentStream({
      model: modelId, config, contents: prompt,
    });
    let fullText = '';
    for await (const chunk of stream) {
      fullText += (chunk.text || '');
      onProgress(fullText);
    }
    return injectTemplates(JSON.parse(fullText) as GeneratedContent);
  }

  const response = await ai.models.generateContent({ model: modelId, config, contents: prompt });
  const text = response.text;
  if (!text) throw new Error("No content generated by AI.");
  return injectTemplates(JSON.parse(text) as GeneratedContent);
};

export const generateWebsite = async (
  prompt: string,
  preferredModelId: string,
  onProgress?: (partial: string, activeModel?: string) => void
): Promise<{ content: GeneratedContent; usedModel: string }> => {
  const ai = getClient();

  // Build model priority list: preferred first, then others as fallback
  const allModelIds = AVAILABLE_MODELS.map(m => m.id);
  const fallbackOrder = [
    preferredModelId,
    ...allModelIds.filter(id => id !== preferredModelId),
  ];

  let lastError: any = null;

  for (const modelId of fallbackOrder) {
    // Skip if this model is currently quota-blocked
    if (isQuotaBlocked(modelId)) {
      const waitSecs = getQuotaWaitSeconds(modelId);
      console.warn(`Skipping ${modelId} — quota blocked for ${waitSecs}s more`);
      continue;
    }

    const MAX_RETRIES = 2; // Fewer retries per model since we have fallbacks
    for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
      try {
        onProgress?.('', modelId); // Signal which model we're trying
        const content = await tryGenerateWithModel(ai, modelId, prompt, onProgress);
        return { content, usedModel: modelId };

      } catch (error: any) {
        lastError = error;
        const raw = error.message || error.toString();
        const msg = raw.toLowerCase();

        console.warn(`[${modelId}] Attempt ${attempt + 1} failed:`, msg.slice(0, 120));

        // Fatal errors — stop everything
        if (isFatalError(msg)) throw wrapError(lastError);

        // 404 — this model doesn't exist, skip to next
        if (isNotFoundError(msg)) break;

        // Quota / rate limit — mark model blocked and try next model
        if (isQuotaError(msg)) {
          markQuotaHit(modelId);
          break; // Move to next model immediately
        }

        // Retryable error (503, 500, network) — wait then retry same model
        if (attempt < MAX_RETRIES - 1) {
          await wait(1500 * (attempt + 1));
          continue;
        }
        break;
      }
    }
  }

  // All models failed or all blocked
  const msg = (lastError?.message || String(lastError)).toLowerCase();

  if (msg === 'api_key_missing') throw new Error("API_KEY_MISSING");
  if (isAuthError(msg)) throw new Error("API_KEY_INVALID");

  // Check if ALL models are quota-blocked
  const allBlocked = fallbackOrder.every(id => isQuotaBlocked(id));
  if (allBlocked) {
    const minWait = Math.min(...fallbackOrder.map(id => getQuotaWaitSeconds(id)));
    throw new Error(`QUOTA_ALL_BLOCKED:${minWait}`);
  }

  if (isQuotaError(msg)) {
    throw new Error(`QUOTA_ALL_BLOCKED:60`);
  }
  if (msg.includes('503') || msg.includes('overloaded')) {
    throw new Error("AI service is temporarily busy. Please try again in a moment.");
  }

  throw new Error(lastError?.message || "Failed to generate website. Please try again.");
};

function wrapError(error: any): Error {
  const msg = (error?.message || String(error)).toLowerCase();
  if (msg === 'api_key_missing') return new Error("API_KEY_MISSING");
  if (isAuthError(msg)) return new Error("API_KEY_INVALID");
  return error instanceof Error ? error : new Error(String(error));
}

function injectTemplates(content: GeneratedContent): GeneratedContent {
  if (content.html) {
    content.html = content.html
      .replace(/<!--__TEMPLATE_CONTACT__-->/g, CONTACT_TEMPLATE)
      .replace(/<!--__TEMPLATE_FOOTER__-->/g, FOOTER_TEMPLATE);
  }
  return content;
}

// ─────────────────────────────────────────────────────────────────────────────
// SEO AGENT
// ─────────────────────────────────────────────────────────────────────────────

export const optimizeSEO = async (
  generatedHtml: string,
  userPrompt: string
): Promise<{ improvedHtml: string; seoReport: string }> => {
  try {
    const ai = getClient();
    // Use first non-blocked model for SEO
    const seoModel = AVAILABLE_MODELS.find(m => !isQuotaBlocked(m.id))?.id || DEFAULT_MODEL;

    const response = await ai.models.generateContent({
      model: seoModel,
      config: {
        systemInstruction: `You are an elite SEO specialist. Analyze the HTML and:
1. Add/improve meta tags (title, description, og:tags, twitter:card, canonical)
2. Add JSON-LD structured data
3. Fix semantic HTML (h1→h6 hierarchy, aria-labels, img alt texts)
4. Add rel="noopener noreferrer" to external links
Return ONLY valid JSON: { "improvedHtml": "...", "seoReport": "bullet list of changes" }`,
        temperature: 0.1,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            improvedHtml: { type: Type.STRING },
            seoReport: { type: Type.STRING },
          },
          required: ["improvedHtml", "seoReport"],
        },
      },
      contents: `Website Intent: ${userPrompt}\n\nHTML:\n${generatedHtml.slice(0, 8000)}`,
    });

    const result = JSON.parse(response.text || '{}');
    return {
      improvedHtml: result.improvedHtml || generatedHtml,
      seoReport: result.seoReport || "No changes made.",
    };
  } catch {
    return { improvedHtml: generatedHtml, seoReport: "SEO optimization unavailable." };
  }
};

export const enhancePrompt = async (simpleIdea: string): Promise<string> => {
  try {
    const ai = getClient();
    const model = AVAILABLE_MODELS.find(m => !isQuotaBlocked(m.id))?.id || DEFAULT_MODEL;
    const response = await ai.models.generateContent({
      model,
      config: {
        systemInstruction: `Expand the user's short idea into a detailed, professional website prompt in 3-4 sentences. Output ONLY the prompt text.`,
        temperature: 0.7,
        maxOutputTokens: 256,
      },
      contents: `Expand: ${simpleIdea}`,
    });
    return response.text || simpleIdea;
  } catch {
    return simpleIdea;
  }
};
