
import { GoogleGenAI, Type, Schema } from "@google/genai";
import { SYSTEM_INSTRUCTION, DEFAULT_MODEL } from "../constants";
import { GeneratedContent } from "../types";

// Helper to get client (Lazy init ensures process.env is ready)
const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
      throw new Error("API Key is missing in the application environment.");
  }
  return new GoogleGenAI({ apiKey });
}

const responseSchema: Schema = {
  type: Type.OBJECT,
  properties: {
    html: { type: Type.STRING, description: "Complete HTML structure with Tailwind classes." },
    css: { type: Type.STRING, description: "Leave empty for speed." },
    javascript: { type: Type.STRING, description: "Leave empty for speed." },
  },
  required: ["html", "css", "javascript"],
};

// Utility to pause execution
const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * Generates a website based on the user's prompt.
 * Includes Retry Logic for robustness against Rate Limits (429) and Server Overload (503).
 */
export const generateWebsite = async (
  prompt: string,
  modelId: string
): Promise<GeneratedContent> => {
  const ai = getClient();
  const MAX_RETRIES = 3;
  let lastError: any = null;

  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    try {
      const response = await ai.models.generateContent({
        model: modelId,
        config: {
          systemInstruction: SYSTEM_INSTRUCTION,
          temperature: 0.7, // Higher temp often yields creative results faster without getting stuck on logic
          responseMimeType: "application/json",
          responseSchema: responseSchema,
        },
        contents: prompt,
      });

      const text = response.text;
      
      if (!text) {
        throw new Error("No content generated by AI.");
      }

      // Parse the JSON response
      try {
        const content = JSON.parse(text) as GeneratedContent;
        // Fallback for speed optimization if AI sends nulls
        if (!content.css) content.css = "";
        if (!content.javascript) content.javascript = "";
        return content;
      } catch (parseError) {
        console.warn(`Attempt ${attempt + 1}: JSON parse failed.`, text);
        throw new Error("Received invalid JSON data from AI.");
      }

    } catch (error: any) {
      lastError = error;
      const msg = (error.message || error.toString()).toLowerCase();
      
      console.warn(`Generation Attempt ${attempt + 1} failed:`, msg);
      
      // CRITICAL: Identify Non-Retriable Errors
      // 400: Invalid Argument, 401/403: Auth/Permissions, 404: Model Not Found
      if (msg.includes('400') || msg.includes('401') || msg.includes('403') || msg.includes('404') || msg.includes('key') || msg.includes('invalid argument')) {
         // Break loop to report error immediately
         break;
      }

      // RETRIABLE ERRORS
      // 429: Rate Limit/Quota, 503: Service Unavailable, 500: Internal Error, or Fetch failures
      if (attempt < MAX_RETRIES - 1) {
        // Exponential backoff: 1000ms, 2000ms, 4000ms
        const delay = 1000 * Math.pow(2, attempt);
        await wait(delay);
        continue;
      }
    }
  }

  // If we get here, all retries failed. Throw a user-friendly error.
  const msg = (lastError?.message || String(lastError)).toLowerCase();

  // 1. Quota / Rate Limit
  if (msg.includes('429') || msg.includes('quota') || msg.includes('resource exhausted')) {
      throw new Error("High Traffic: System limit exceeded. Please wait 30 seconds and try again.");
  }
  
  // 2. Auth Errors
  if (msg.includes('401') || msg.includes('403') || msg.includes('key')) {
      throw new Error("API Key Error. Please check your API Key configuration in Google AI Studio.");
  }
  
  // 3. Server Errors
  if (msg.includes('503') || msg.includes('overloaded') || msg.includes('internal')) {
      throw new Error("AI Service is temporarily busy. Please try again.");
  }
  
  // 4. Safety Filters
  if (msg.includes('candidate') || msg.includes('safety') || msg.includes('blocked')) {
      throw new Error("The request was blocked by safety filters. Please try a different prompt.");
  }

  // 5. Generic Fallback
  throw new Error(lastError?.message || "Failed to generate website. Please try again.");
};

/**
 * Expands a simple idea into a detailed professional prompt.
 */
export const enhancePrompt = async (simpleIdea: string): Promise<string> => {
  try {
    const ai = getClient();
    
    const response = await ai.models.generateContent({
      model: DEFAULT_MODEL,
      config: {
        systemInstruction: `You are an expert web consultant. Expand the user's short website idea into a detailed, professional prompt. Output ONLY the prompt text.`,
        temperature: 0.8,
      },
      contents: `Expand: ${simpleIdea}`,
    });

    return response.text || simpleIdea;
  } catch (error) {
    console.error("Prompt Enhancement Error:", error);
    // Silent fail for enhancement is better than blocking the UI
    return simpleIdea; 
  }
};
